from .mailbox_routes import mailbox_bp
from .hpc_routes import hpc_bp
from .email_routes import email_bp
from .template_routes import template_bp
from .routes import routes_bp
from .contact_routes import contact_bp
from .hpc_quota_routes import quota_bp
from .login_routes import login_bp
from .setting_routes import setting_bp
from .permission_routes import permission_bp
from .billing_routes import billing_bp
from .profile_routes import profile_bp